{
 "title": "Nursery Telemetry",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartgarden\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"dashboard_summary\" and\n    r._field == \"text\"\n  )"
    }
   ]
  },
  {
   "title": "Nursery Soil Moisture",
   "type": "timeseries",
   "description": "The soil moisture of the plant beds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"smartgarden\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"nursery\" and\n    r._field == \"soilMoisture\"\n  )"
    },
    {
     "query": "from(bucket: \"smartgarden\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"nursery\" and\n    r._field == \"soilMoisture\"\n  )"
    }
   ]
  },
  {
   "title": "Soil Moisture Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartgarden\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"nursery\" and\n    r._field == \"soilMoisture\"\n  )"
    }
   ]
  },
  {
   "title": "Nursery Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"smartgarden\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"nursery\" and\n    r._field == \"temperature\"\n  )"
    }
   ]
  },
  {
   "title": "Temperature Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartgarden\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"nursery\" and\n    r._field == \"temperature\"\n  )"
    }
   ]
  },
  {
   "title": "Nursery CO2 Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"smartgarden\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"nursery\" and\n    r._field == \"co2Level\"\n  )"
    }
   ]
  },
  {
   "title": "CO2 Level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartgarden\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"nursery\" and\n    r._field == \"co2Level\"\n  )"
    }
   ]
  }
 ]
}